TemplateDoesNotExist at /users/mentors/5/
mentors/profile.html
Request Method:	GET
Request URL:	http://fe6c2ab6-9cc3-4d2b-863d-f20666b8a8f8-00-3mse50bj99d1k.spock.replit.dev/users/mentors/5/
Django Version:	5.2.1
Exception Type:	TemplateDoesNotExist
Exception Value:	
mentors/profile.html
Exception Location:	/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py, line 47, in select_template
Raised during:	apps.users.views.MentorDetailView
Python Executable:	/home/runner/workspace/.pythonlibs/bin/python
Python Version:	3.11.10
Python Path:	
['/home/runner/workspace',
 '/home/runner/workspace',
 '/nix/store/lc7qv2ldzrs1aq3hbyzmbgvn0h2w26pl-sitecustomize/lib/python/site-packages',
 '/nix/store/dfg63lldbvcj207iyr9z0xw21d8ax02n-python3.11-pip-24.0/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python311.zip',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/lib-dynload',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/wblvmd5y7izx0z10d1w7ga7zc4apjxmb-python3.11-setuptools-75.1.1/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_vendor']
Server time:	Tue, 13 May 2025 10:48:34 +0000
Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /home/runner/workspace/templates/mentors/profile.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/admin/templates/mentors/profile.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/auth/templates/mentors/profile.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/rest_framework/templates/mentors/profile.html (Source does not exist)
Traceback Switch to copy-and-paste view
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py, line 220, in _get_response
                response = response.render()
                                ^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/response.py, line 114, in render
            self.content = self.rendered_content
                                ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/response.py, line 90, in rendered_content
        template = self.resolve_template(self.template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/response.py, line 72, in resolve_template
            return select_template(template, using=self.using)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py, line 47, in select_template
        raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars